// Auto-generated by OpenLane
module top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input valid,
  output ready,
  input write,
  input[7:0] addr,
  input[31:0] wdata,
  output[31:0] rdata
);
endmodule
