SIM = icarus
TOPLEVEL_LANG = verilog

VERILOG_SOURCES = $(PWD)/int8_gemm_core.sv

TOPLEVEL = int8_gemm_core
MODULE = test_int8_gemm_core

WAVES = 1

include $(shell cocotb-config --makefiles)/Makefile.sim
